export const FETCH_POSTS = "FETCH_POSTS";

export const FETCH_MESSAGES = "FETCH_MESSAGES";
export const FETCH_REMOVED_MESSAGE_IDS = "FETCH_REMOVED_MESSAGE_IDS";

export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";
